services:
  clmm_liquidity_stability_postgres:
    image: postgres:16
    container_name: clmm_liquidity_stability_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: clmm_liquidity_stability_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - clmm_liquidity_stability_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d clmm_liquidity_stability_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - clmm_liquidity_stability_network

volumes:
  clmm_liquidity_stability_postgres_data:

networks:
  clmm_liquidity_stability_network:
